using AutoMapper;
using RubyRangersLMS_API.Dtos;
using RubyRangersLMS_API.Dtos.ActivityDtos;
using RubyRangersLMS_API.Dtos.CourseDtos;
using RubyRangersLMS_API.Dtos.ModuleDtos;
using RubyRangersLMS_API.Entities;

namespace RubyRangersLMS_API.Data
{
    public class LmsMappings : Profile
    {
        public LmsMappings()
        {
            CreateMap<Student, StudentDto>();
            CreateMap<StudentDto, Student>();
        }
    }
    public class CourseMappingProfile : Profile
    {
        public CourseMappingProfile()
        {
            CreateMap<CourseDtoGet, Course>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)) // Assuming Id is set in DTO
              .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
              .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
              .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
              .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
              .ForMember(dest => dest.TeacherId, opt => opt.MapFrom(src => src.TeacherId))
              .ForMember(dest => dest.Modules, opt => opt.MapFrom(src => src.Modules));

            CreateMap<Course, CourseDtoGet>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)) // Assuming Id is set in DTO
              .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
              .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
              .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
              .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
              .ForMember(dest => dest.TeacherId, opt => opt.MapFrom(src => src.TeacherId))
              .ForMember(dest => dest.Modules, opt => opt.MapFrom(src => src.Modules));

            CreateMap<CourseDtoPost, Course>()
              .ForMember(dest => dest.Id, opt => opt.Ignore()) // Ignore ID as it will be generated by the database
              .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
              .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
              .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
              .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
              .ForMember(dest => dest.TeacherId, opt => opt.MapFrom(src => src.TeacherId))
              .ForMember(dest => dest.Modules, opt => opt.MapFrom(src => src.Modules));

            // Reverse mapping from Course to CourseDtoPost
            CreateMap<Course, CourseDtoPost>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)) // Include ID in the DTO for updating purposes
              .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
              .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
              .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
              .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
              .ForMember(dest => dest.TeacherId, opt => opt.MapFrom(src => src.TeacherId))
              .ForMember(dest => dest.Modules, opt => opt.MapFrom(src => src.Modules));
        }
    }

    public class ModuleMappingProfile : Profile
    {
        public ModuleMappingProfile()
        {
            CreateMap<ModuleDtoGet, Module>()
               .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
               .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
               .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
               .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
               .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
               .ForMember(dest => dest.CourseId, opt => opt.MapFrom(src => src.CourseId))
               .ForMember(dest => dest.Activities, opt => opt.MapFrom(src => src.Activities));

            CreateMap<Module, ModuleDtoGet>()
               .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
               .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
               .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
               .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
               .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
               .ForMember(dest => dest.CourseId, opt => opt.MapFrom(src => src.CourseId))
               .ForMember(dest => dest.Activities, opt => opt.MapFrom(src => src.Activities));

            CreateMap<Module, ModuleDtoPost>()
               .ForMember(dest => dest.Id, opt => opt.Ignore())
               .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
               .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
               .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
               .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
               .ForMember(dest => dest.CourseId, opt => opt.MapFrom(src => src.CourseId))
               .ForMember(dest => dest.Activities, opt => opt.MapFrom(src => src.Activities))
               .AfterMap((src, dest) =>
               {
                   foreach (var activity in dest.Activities)
                   {
                       activity.ModuleId = src.Id;
                   }
               });

            CreateMap<ModuleDtoPost, Module>()
               .ForMember(dest => dest.Id, opt => opt.Ignore())
               .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
               .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
               .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
               .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
               .ForMember(dest => dest.CourseId, opt => opt.Ignore());
        }
    }
    public class ActivityMappingProfile : Profile
    {
        public ActivityMappingProfile()
        {
            CreateMap<ActivityDtoGet, Activity>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
              .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
              .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
              .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
              .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
              .ForMember(dest => dest.ModuleId, opt => opt.MapFrom(src => src.ModuleId));

            // Mapping for Activity to ActivityDtoGet
            CreateMap<Activity, ActivityDtoGet>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
              .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
              .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
              .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
              .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
              .ForMember(dest => dest.ModuleId, opt => opt.MapFrom(src => src.ModuleId));

            CreateMap<Activity, ActivityDtoPost>()
               .ForMember(dest => dest.Id, opt => opt.Ignore())
               .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
               .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
               .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
               .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
               .ForMember(dest => dest.ModuleId, opt => opt.MapFrom(src => src.ModuleId));

            CreateMap<ActivityDtoPost, Activity>()
               .ForMember(dest => dest.Id, opt => opt.Ignore())
               .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
               .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
               .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate))
               .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate))
               .ForMember(dest => dest.ModuleId, opt => opt.Ignore());
        }
    }
}